applications:
  kafka:
    channel: edge
    charm: kafka-k8s
    constraints: arch=amd64
    resources:
      jmx-prometheus-jar: 1
      kafka-image: 1
    revision: 68
    scale: 3
    storage:
      data: kubernetes,1,1024M
  zookeeper:
    channel: edge
    charm: zookeeper-k8s
    constraints: arch=amd64
    resources:
      zookeeper-image: 2
    revision: 65
    scale: 3
    storage:
      data: kubernetes,1,1024M
bundle: kubernetes
relations:
- - kafka:zookeeper
  - zookeeper:zookeeper
